k: 16
sz: 252
LR: 1e-4
BETA1: 0.9
BETA2: 0.999
NUM_GPU: 1
DATASET_ROOT: "/home/vgl/Research/DNQA/challenge"
BATCH_SIZE: 8
EPOCHS: 100
IMAGE_SIZE: 640
SCHEDULER_STEP: [20, 28]
SCHEDULER_GAMMA: 0.1
SCHEDULER_TYPE: "cosine"
SCHEDULER_T_0: 35
SHUFFLE: True
NUM_WORKERS: 1
CKPT_DIR: "./ckpts"
INIT_FROM: null
PROJECT_NAME: "dnqa-challenge"
LOG_DIR: "./logs"
ENTITY: "vvgl-ozu"