k: 16
sz: 252
LR: 2e-4
BETA1: 0.9
BETA2: 0.999
NUM_GPU: 1
DATASET_ROOT: "/home/vgl/Research/DNQA/challenge"
IMG_SIZE: 256
BATCH_SIZE: 16
EPOCHS: 32
LAMBDA: 10
SCHEDULER_STEP: 3
SCHEDULER_GAMMA: 0.1
VISUALIZE_STEP: 134
SHUFFLE: True
NUM_WORKERS: 1
CKPT_DIR: "./ckpts"
INIT_FROM: null
PROJECT_NAME: "dnqa-challenge"
LOG_DIR: "./logs"
ENTITY: "vvgl-ozu"